services:
  chatsettingschecker:
    image: "ghcr.io/wissididom/chatsettingschecker"
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
    env_file: .env
